// ---------------------------------------------------------------------------
// NLEX corridor traffic microsimulation.
//
// Each vehicle is an independent agent. Longitudinal motion uses the
// Intelligent Driver Model (IDM); lane changes use a MOBIL-style decision.
// Congestion (queues, stop-and-go waves, merge bottlenecks) is EMERGENT from
// these local rules — nothing is scripted. Interventions (lane closures,
// incidents, speed limits) change the road; the agents react on their own.
//
// Units are SI internally (metres, seconds, m/s); the UI converts to km/h.
// A seeded RNG makes a run reproducible, so a baseline and an intervention
// can be compared on the identical inflow sequence.
// ---------------------------------------------------------------------------

export type VehicleClass = 1 | 2 | 3;
export type DriverProfile = "cautious" | "normal" | "aggressive";

export type Vehicle = {
  id: number;
  lane: number;
  x: number; // metres from segment start
  v: number; // m/s
  vClass: VehicleClass;
  profile: DriverProfile;
  v0: number; // desired free-flow speed (m/s)
  /* Per-driver traits, drawn once at birth.
   *
   * These used to be read from PROFILE[profile] at every step, which meant a
   * "normal" driver was not a driver at all but a category: every normal Class
   * 1 car wanted exactly 30.0 m/s, left exactly 1.4 s of headway and
   * accelerated at exactly 1.4 m/s². Three classes times three profiles gave
   * the whole road nine possible behaviours, and on an open carriageway the
   * cars in each group converged on an identical speed and held formation.
   *
   * Real drivers vary continuously, and they vary WITHIN a temperament: two
   * unhurried drivers still do not want the same speed. Sampling each trait
   * per vehicle is what makes a queue disperse, a platoon stretch, and a
   * faster driver actually come up behind a slower one and have a reason to
   * change lane. */
  T: number; // preferred time headway (s)
  aMax: number; // this driver's comfortable acceleration (m/s²)
  politeness: number; // MOBIL: weight given to the drivers they affect
  lcSec: number; // seconds this vehicle takes to cross a lane line
  /* When this driver next looks for a gap.
   *
   * Without these, every agent re-evaluated a lane change on every 0.05 s
   * tick — 20 perfectly synchronised glances a second, each one omniscient
   * and instantaneous. That is the single least human thing a microsimulation
   * does: the moment a gap becomes worth taking, everybody who could take it
   * knows at the same instant. `scanSec` is this driver's own mirror-check
   * cadence and `scanTimer` their phase within it, so they notice
   * opportunities at different moments and some are simply slower to spot
   * one than the car behind them. */
  scanSec: number;
  scanTimer: number;
  /* Perception-reaction lag.
   *
   * IDM as written responds to the vehicle ahead instantaneously and
   * continuously, which no human does. That is why the queues it produces
   * glide smoothly instead of oscillating: real stop-and-go waves — the
   * phantom jams you sit in on a motorway with no crash to explain them — are
   * generated by exactly this lag, drivers braking slightly harder than the
   * car in front because they saw it late.
   *
   * Modelled as an asynchronous update (the "action point" approach) rather
   * than by storing a history of the leader's state: the driver recomputes
   * their acceleration every `reactionS` and holds it in between. Same
   * delayed response, a fraction of the memory. */
  reactionS: number;
  reactTimer: number;
  accel: number; // the acceleration currently being held

  /** How long this driver will sit at a taper before forcing their way in. */
  patience: number;
  /** Which ramp this vehicle intends to leave by; null = runs the full length. */
  exitAtX: number | null;
  /** How long they have been stopped in a lane that is closing. */
  stuckFor: number;
  length: number; // m
  spawnTime: number; // sim seconds
  co2: number; // grams emitted so far
  laneCooldown: number; // seconds until next lane change allowed
  /* Where the vehicle is drawn across the carriageway, as opposed to which
   * lane it belongs to.
   *
   * `lane` changes the instant MOBIL accepts the move, because every following
   * and safety calculation needs one unambiguous answer to "which lane is this
   * in" — a car half-way across belongs to one of them, not to both. But the
   * renderer read that same integer, so a change moved the sprite a whole lane
   * width between two frames and looked like a teleport.
   *
   * These two carry the movement the integer cannot: `laneFrom` is where the
   * manoeuvre started and `laneShift` runs 0 → 1 over `lcSec`. The
   * physics is unaffected — this is presentation only. */
  laneFrom: number;
  laneShift: number;
  color: string; // the agent's own paint — class hue with per-vehicle variation
};

export type Interventions = {
  closedLanes: boolean[]; // per-lane
  /**
   * Where a closure begins, in metres from the start of the simulated span.
   * Traffic must merge out before reaching it.
   */
  closurePoint: number;
  /**
   * Where it ends and the lane reopens. Roadworks occupy a stretch, not a
   * half-line: an operator closing lane 4 from km 0.20 to km 0.40 expects the
   * lane back afterwards, and the tailback to clear once traffic is past it.
   * Defaults to the end of the span, which is the old open-ended behaviour.
   */
  closureEnd: number;
  /**
   * Display only — draw the closure stretch as a dashed outline even though no
   * lane is closed. A closure acts on closed lanes alone, so without this an
   * operator who set the stretch first saw nothing happen.
   */
  showClosurePreview?: boolean;
  /**
   * Display only — the stretch being drawn with two clicks, in metres from the
   * start of the span, before the second click commits it.
   */
  closureDraft?: { from: number; to: number } | null;
  incidents: { lane: number; x: number }[]; // stalled obstacles
  speedLimitKmh: number | null; // applies in the speed zone
  speedZone: [number, number]; // [from, to] metres
};

export type Metrics = {
  activeAgents: number;
  avgSpeedKmh: number;
  throughputPerMin: number; // vehicles completing the segment, extrapolated
  densityPerKmLane: number;
  stoppedCount: number;
  longestQueueM: number;
  co2RatePerMin: number; // kg CO2 / minute (current)
  avgTravelTimeS: number; // of recently completed vehicles
  completed: number;
  elapsedS: number; // simulated seconds since this run began
  /** False until the warm-up has elapsed; statistics before that are not
   *  comparable with anything, because the road is still filling. */
  warm: boolean;
  /* Demand that could not get onto the segment, veh/h.
   *
   * When demand exceeds what the road can take, the surplus queues UPSTREAM of
   * the simulated stretch, where nothing draws it and no metric sees it. The
   * segment itself then reports a perfectly healthy speed, because the only
   * traffic on it is the traffic that fitted. Measured at 3,000 veh/h/lane of
   * demand the road read 78 km/h while a quarter of the vehicles never got on.
   * Reporting this is the difference between "the road is fine" and "the road
   * is fine because we left a quarter of the demand at the door". */
  unmetVehPerHour: number;
};

export type SimConfig = {
  length: number; // segment length (m)
  laneCount: number;
  inflowVehPerHour: number; // total across all open lanes
  seed: number;
  /** Per-class CO2 (g/m) and fleet share, from the warehouse.
   *
   *  The constants below are defaults so the simulation still runs standalone,
   *  but they are NOT the corridor's numbers: they had Class 3 at 950 g/km
   *  against the 1,492 in nlex_emission_factors, and the fleet at 78/16/6
   *  against an observed 78.1/13.0/8.9. Supplying this makes the sandbox agree
   *  with the Emissions dashboard instead of quietly contradicting it. */
  classProfile?: Partial<Record<VehicleClass, { co2PerM?: number; share?: number }>>;
  /* How long to let the road fill before statistics mean anything.
   *
   * A run starts with an empty carriageway, so for the first minute or so
   * there is nothing on it to slow anyone down and nobody has yet reached the
   * far end. Average speed therefore starts at free flow and falls, and
   * throughput starts at zero and climbs — neither is a property of the
   * scenario, both are artefacts of starting from nothing. Measuring through
   * that transient is the classic way to get a flattering answer out of a
   * microsimulation. Statistics are collected only after it. */
  warmupS?: number;
  /** Ramps along the segment: where traffic joins and leaves. */
  ramps?: RampSpec[];
};

/** An interchange on the simulated stretch: traffic joins, leaves, or both. */
export type RampSpec = {
  /** Distance along the segment, metres from the entry end. */
  x: number;
  /** Vehicles per hour joining here. */
  onVehPerHour: number;
  /** Share of passing traffic that leaves here, 0–1. */
  offFraction: number;
  /** Exit name, for debugging and tooltips. */
  name: string;
};

// Per-class kinematics. Heavier = slower desired speed, longer, more CO2/km.
// Colours are a colourblind-safe categorical trio (validated) so each class is
// identifiable at a glance; red is deliberately avoided (it marks a stopped car).
// `lcSec` is how long this class takes to cross a lane line — see
// LANE_CHANGE_BASE_SEC. It scales with size, not mass: a 14 m articulated
// truck has slower steering, has to swing its trailer, and is driven across
// gently because the load shifts. A hatchback just goes.
const CLASS = {
  1: { v0: 30, len: 4.6, co2PerM: 0.16, color: "#3e67ef", share: 0.78, lcSec: 1.1 }, // light — blue
  2: { v0: 25, len: 9, co2PerM: 0.55, color: "#1f9d57", share: 0.16, lcSec: 1.9 }, // medium — green
  3: { v0: 22, len: 14, co2PerM: 0.95, color: "#9b5de5", share: 0.06, lcSec: 2.7 }, // heavy — purple
} as const;

// Driver profile modifiers: time headway T, desired-speed factor, politeness.
// `lcf` scales how briskly this temperament steers across. Someone who tailgates
// and takes small gaps also changes lanes decisively; a cautious driver eases over.
// `scanf` scales the mirror-check cadence. An aggressive driver is actively
// hunting for a gap and so notices one sooner; a cautious driver is settled in
// their lane and looks less often.
//
// CALIBRATION NOTE — the T values.
// Time headway is the parameter that sets capacity: at equilibrium a lane
// carries v / (S0 + length + v*T) vehicles per second, so T is the only free
// parameter with a direct line to the one quantity that CAN be checked against
// published figures. With the original 1.8 / 1.4 / 1.0 the simulated basic
// freeway capacity measured 2,435 pc/h/lane against the HCM's 2,000-2,400, so
// they are scaled by 1.12 to bring it inside the range. Every value stays
// within the 0.8-2.0 s that the car-following literature reports for motorway
// headway, so this is a calibration, not a fudge.
// See All_Scripts/Simulation_Validation/validate_sandbox.ts.
const PROFILE = {
  cautious: { T: 2.0, v0f: 0.92, politeness: 0.5, lcf: 1.16, scanf: 1.15, pat: 1.5, react: 1.2 },
  normal: { T: 1.57, v0f: 1.0, politeness: 0.3, lcf: 1.0, scanf: 1.0, pat: 1.0, react: 1.0 },
  aggressive: { T: 1.12, v0f: 1.12, politeness: 0.1, lcf: 0.85, scanf: 0.8, pat: 0.6, react: 0.82 },
} as const;

// IDM constants
const A_MAX = 1.4; // max accel m/s^2
const B_COMF = 2.0; // comfortable decel m/s^2
const S0 = 2.5; // minimum bumper gap m
const DELTA = 4;
const INCIDENT_LENGTH = 5; // a stalled vehicle occupies ~5 m of lane

const B_SAFE = 4.0; // MOBIL: max decel a follower may be forced into
const LC_THRESHOLD = 0.2; // MOBIL: incentive threshold m/s^2
const LC_BIAS_ESCAPE = 3.0; // strong pull to leave a lane that's blocked ahead

/* ── Zipper merge ────────────────────────────────────────────────────────────
 *
 * A closed lane is a stopped obstacle at its taper, so traffic in it slows and
 * eventually stops. That created a deadlock: merging from a standstill into a
 * lane still running at 70 km/h forces the new follower to brake far harder
 * than B_SAFE, the safety veto refused every such move, and the queue in the
 * closed lane then grew without bound — cars sat at the taper looking like the
 * closure had broken the simulation. Arrivals ran at one car every 2.4 s while
 * merges only happened on the rare huge gap, about one every 7 s.
 *
 * Real drivers resolve this by pushing in, and the lane being merged into
 * yields. So a MANDATORY merge is allowed to impose a harder deceleration than
 * a discretionary one, scaled by how close the vehicle is to the taper: far
 * upstream it behaves normally and waits for a civilised gap; at the taper it
 * takes what it can get. B_SAFE still applies in full to ordinary lane
 * changes, and even a forced merge is capped — this buys a zipper, not a
 * collision.
 */
const MERGE_ZONE_M = 150; // over what distance the urgency ramps to 1
/* How much a driver eases off approaching a lane drop in a NEIGHBOURING lane.
 *
 * A closure does not only affect the lane that is shut. Drivers in the open
 * lanes beside it see the merge coming, lift off and leave room, so the whole
 * carriageway slows and the queue spreads across lanes — which is why a lane
 * drop costs far more capacity than the one lane it removes.
 *
 * Without this the model kept the effect unrealistically local: with a middle
 * lane closed, the lane on one side sat at 61 km/h while the lane on the other
 * side ran at 80.8 km/h, completely undisturbed, because every merge happened
 * to go the other way. Measured against no closure at all, that lane may as
 * well not have known. */
const MERGE_CAUTION = 0.62; // desired-speed multiplier at the taper itself

/* ── Lane discipline: keep right except to overtake ──────────────────────────
 *
 * MOBIL as written here was symmetric — a lane change happened only when it
 * bought acceleration, and staying put cost nothing. So a slow driver who
 * happened to spawn in lane 1 stayed in lane 1 for the whole run, and the
 * "overtaking lane" carried the same mix and very nearly the same speed as the
 * rest of the carriageway. Nothing in the model knew the inner lane means
 * anything.
 *
 * The standard fix is an asymmetric bias: moving outward is rewarded, moving
 * inward is charged. A driver held up by someone slower still pulls in to
 * overtake, because the acceleration they gain exceeds the bias — and once
 * past, the same bias pushes them back out. Lane discipline is then emergent
 * rather than scripted, and it produces the speed gradient a real motorway has
 * without assigning any lane its own speed.
 *
 * Sized well below LC_BIAS_ESCAPE: leaving a closing lane must always outrank
 * a matter of courtesy.
 */
const LANE_DISCIPLINE = 0.32; // m/s^2 in favour of the outer lane
const B_SAFE_FORCED = 9.0; // decel a yielding follower will tolerate at the taper

/** How long a lane change takes to draw, in simulation seconds.
 *
 *  A real lane change runs about 3–5 s door to door for a car, and longer
 *  for a heavy vehicle. That is too slow here: the camera watches a 1 km span,
 *  so a car crossing for four seconds spends most of the visible road
 *  straddling a line and reads as indecision rather than a manoeuvre. Times
 *  are compressed, but the RATIO between classes is kept, because that ratio
 *  is the part you can see — a bus that slides over as fast as a hatchback is
 *  the single thing that most gives away a toy simulation.
 *
 *  This is a base for class 1 only. The figure actually used is per vehicle
 *  (`v.lcSec`), from the class size and the driver's temperament, and the
 *  cooldown after a change is derived from it so that no vehicle can ever
 *  begin a second manoeuvre while still drawn mid-way through the first. */
const LANE_CHANGE_BASE_SEC = 1.1;

/* Quiet time after completing a change, on top of the crossing itself. Keeps a
 * vehicle from weaving lane to lane and gives the new follower a moment to
 * settle before anything else is decided around it. */
const LC_SETTLE_SEC = 0.9;

/* Base interval between one driver's glances for a gap. Around a second, which
 * is the order of a real mirror-check-and-decide cycle, and short enough that
 * a vehicle still reacts promptly to a closure ahead (where the cadence is
 * tightened — see step()). */
const SCAN_BASE_SEC = 0.85;

/* How much more often a driver looks when their own lane is closing ahead.
 * Someone who has seen the merge sign is watching the next lane continuously,
 * not glancing at it once a second. */
const SCAN_ALERT_FACTOR = 4;

/* ── Zipper merge at crawling pace ───────────────────────────────────────────
 *
 * Below this speed a merge stops being an IDM problem and becomes a question
 * of whether the vehicle physically fits. ~11 km/h: queue pace. */
const CREEP_SPEED = 3.0; // m/s
/** Clear road a creeping vehicle needs ahead of it before it noses in. */
const CREEP_GAP = 1.5; // m

/** What a heavy vehicle is charged for using a lane it is barred from. Large
 *  enough that any workable permitted lane outranks it. */
const RESTRICTED_LANE_PENALTY = 2.5;

/* ── Forcing in ──────────────────────────────────────────────────────────────
 *
 * A driver stopped at a taper does not wait indefinitely for a gap that
 * satisfies everyone. After a while they put their nose out and the through
 * traffic yields — which is the only reason a taper clears at all when the
 * open lane is moving faster than the queue. Without it, a stopped vehicle
 * beside a flowing lane can never merge (you cannot insert a stationary bus in
 * front of a car doing 90) and it blocks its lane for the rest of the run.
 *
 * How long they will wait is a trait, so some drivers nose out after a few
 * seconds and others hold back far longer. */
const PATIENCE_BASE_SEC = 8;

/* When forcing, the gap behind is judged as time-to-collision rather than by
 * IDM comfort: the follower must have enough road to brake in, not enough to
 * brake in comfortably. A follower at 25 m/s needs ~30 m. */
const FORCE_TTC_SEC = 1.2;

/** Hard floor on bumper-to-bumper spacing, enforced after integration purely
 *  so vehicles are never drawn through one another. Not a headway rule. */
const MIN_CLEARANCE = 0.5; // m

/* Base perception-reaction time. The traffic-psychology range for an expected
 * event (the car ahead's brake lights) is roughly 0.6-1.5 s; 0.9 s sits in the
 * middle of it. Scaled per driver and per temperament — see Vehicle.reactionS. */
const REACTION_BASE_SEC = 0.9;

/** Default warm-up if a config does not set one. One minute covers filling a
 *  1 km segment at motorway speed several times over. */
const DEFAULT_WARMUP_S = 60;

/** Most vehicles that may be held waiting to enter. Beyond this the surplus is
 *  reported as unmet demand instead of being stored invisibly. */
const MAX_ENTRY_QUEUE = 5;

/** Typical speed of traffic coming off an acceleration lane (m/s, ~58 km/h).
 *  Below the prevailing speed on purpose: that differential is what makes an
 *  interchange a bottleneck rather than a neutral addition of vehicles. */
const RAMP_JOIN_SPEED = 16;

/** How far ahead of their exit a driver starts working towards the outside
 *  lane. 400 m is about the point the advance sign appears. */
const EXIT_APPROACH_M = 650;

/** Pull towards the exit lane for a vehicle that is leaving soon. Scaled by
 *  how close the exit is, so it grows from a preference into a necessity. */
const LC_BIAS_EXIT = 3.4;

/** Final run-in to a ramp, where a driver stops being polite about gaps. */
const EXIT_COMMIT_M = 250;

/** Slowest a committed driver will ease to while hunting for their gap, as a
 *  fraction of their desired speed. */
const EXIT_CAUTION = 0.7;

/* ── Heavy-vehicle lane restriction ──────────────────────────────────────────
 *
 * Buses and trucks (classes 2 and 3) are kept out of lane index 0 — "L1" on
 * the controls, the innermost lane, drawn at the top of the canvas. Traffic
 * here runs left to right, so lane 0 is the fast lane, and NLEX restricts it to
 * light vehicles.
 *
 * Enforced in three places, because one is not enough: the initial seeding, the
 * spawn at the entrance, and the lane-change decision. Miss the lane-change
 * check and trucks still arrive in L1 a few seconds later by merging into it;
 * miss either of the others and L1 starts the run with trucks already sitting
 * in it.
 */
const HEAVY_MIN_LANE = 1;

/** May this class travel in this lane? */
function laneAllowsClass(vClass: VehicleClass, lane: number): boolean {
  return vClass === 1 || lane >= HEAVY_MIN_LANE;
}

/** Where to draw a vehicle across the carriageway, in lane units.
 *
 *  Smoothstep rather than a straight ramp: a constant-rate slide starts and
 *  stops with a visible corner, which on a small sprite looks like a jerk at
 *  each end. Easing in and out matches how a car is actually steered across. */
export function visualLane(v: Vehicle): number {
  if (v.laneShift >= 1) return v.lane;
  const t = Math.max(0, Math.min(1, v.laneShift));
  return v.laneFrom + (v.lane - v.laneFrom) * (t * t * (3 - 2 * t));
}

/** One draw from a normal distribution, clamped to [lo, hi].
 *
 *  Box–Muller off the simulation's own seeded RNG, so a given seed still
 *  replays exactly — heterogeneity must not cost reproducibility, or two runs
 *  of the same scenario stop being comparable and the baseline capture is
 *  meaningless.
 *
 *  Clamped rather than resampled: a truncated tail is the honest shape here.
 *  Nobody drives at four sigma, and an unclamped draw can go negative, which
 *  for a desired speed or a headway is not a slow driver but a broken one. */
function gauss(rng: () => number, sd: number, lo: number, hi: number): number {
  const u1 = Math.max(1e-9, rng());
  const u2 = rng();
  const z = Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2);
  return Math.min(hi, Math.max(lo, 1 + z * sd));
}

/** The traits that make one driver differ from another of the same temperament.
 *
 *  Spread figures are the ones the traffic-flow literature reports for
 *  free-flow speed on a motorway: a roughly normal distribution with a
 *  coefficient of variation near 10%. Headway and acceleration are given a
 *  wider spread because drivers differ more in how close they sit and how hard
 *  they pull away than in the speed they are aiming for.
 *
 *  Called from both the seeding path and the spawn path. They used to build
 *  vehicles independently, and a trait added to one would silently not exist
 *  on the other — the road would behave differently at the start of a run than
 *  a minute in. */
function makeDriver(rng: () => number, vClass: VehicleClass, profile: DriverProfile) {
  const c = CLASS[vClass];
  const p = PROFILE[profile];
  return {
    // ±10%, so a calm driver may still out-run a hurried one — which is what
    // stops the three profiles reading as three fixed speeds on the canvas.
    v0: c.v0 * p.v0f * gauss(rng, 0.1, 0.72, 1.3),
    T: p.T * gauss(rng, 0.15, 0.65, 1.5),
    aMax: A_MAX * gauss(rng, 0.13, 0.65, 1.4),
    politeness: Math.min(0.85, Math.max(0, p.politeness * gauss(rng, 0.25, 0.3, 1.9))),
    // Size sets the scale, temperament nudges it, and the draw keeps two
    // identical trucks from steering in lockstep.
    lcSec: c.lcSec * p.lcf * gauss(rng, 0.12, 0.72, 1.35),
    scanSec: SCAN_BASE_SEC * p.scanf * gauss(rng, 0.3, 0.45, 1.9),
    // Random phase. Without it every driver created in the same frame would
    // glance in unison, which just moves the lockstep rather than removing it.
    scanTimer: SCAN_BASE_SEC * rng(),
    patience: PATIENCE_BASE_SEC * p.pat * gauss(rng, 0.25, 0.5, 1.8),
    reactionS: REACTION_BASE_SEC * p.react * gauss(rng, 0.22, 0.5, 1.7),
    // Random phase again: without it every driver blinks at the same instant
    // and the lag produces one synchronised shockwave instead of many.
    reactTimer: REACTION_BASE_SEC * rng(),
  };
}

// Blend two hex colours; t=0 → a, t=1 → b.
export function mixHex(a: string, b: string, t: number): string {
  const pa = [parseInt(a.slice(1, 3), 16), parseInt(a.slice(3, 5), 16), parseInt(a.slice(5, 7), 16)];
  const pb = [parseInt(b.slice(1, 3), 16), parseInt(b.slice(3, 5), 16), parseInt(b.slice(5, 7), 16)];
  const c = pa.map((v, i) => Math.round(v + (pb[i] - v) * t));
  return "#" + c.map((v) => v.toString(16).padStart(2, "0")).join("");
}

// A per-agent shade: the class hue nudged lighter or darker, so same-class
// vehicles look individual without losing the family colour that marks class.
function varyColor(hex: string, r: number): string {
  const t = (r - 0.5) * 0.3; // -0.15 .. +0.15
  return t >= 0 ? mixHex(hex, "#ffffff", t) : mixHex(hex, "#0b1226", -t);
}

function mulberry32(seed: number) {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export class TrafficSim {
  cfg: SimConfig;
  vehicles: Vehicle[] = [];
  interventions: Interventions;
  time = 0;
  private rng: () => number;
  private nextId = 1;
  private spawnAccumulator = 0;

  /**
   * Vehicles per lane, ordered by position, rebuilt once per step.
   *
   * Finding the vehicle in front used to scan every vehicle on the road, and
   * it is asked several times per vehicle per step — its own lane, each
   * candidate lane during a lane-change decision, and the prospective follower
   * in that lane. That is quadratic, and at corridor length it dominated: 980
   * vehicles cost 22 ms a step, so the animation could not keep up before any
   * drawing had happened. One sort per lane per step makes each lookup a binary
   * search instead.
   */
  private laneIndex: Vehicle[][] = [];

  private rebuildLaneIndex() {
    const lanes = this.cfg.laneCount;
    this.laneIndex = Array.from({ length: lanes }, () => [] as Vehicle[]);
    for (const v of this.vehicles) {
      if (v.lane >= 0 && v.lane < lanes) this.laneIndex[v.lane].push(v);
    }
    for (const row of this.laneIndex) row.sort((a, b) => a.x - b.x);
  }

  /** First vehicle in `lane` strictly beyond `x`, or null. */
  private firstAfter(lane: number, x: number, exclude?: Vehicle): Vehicle | null {
    const row = this.laneIndex[lane];
    if (!row || row.length === 0) return null;
    let lo = 0;
    let hi = row.length;
    while (lo < hi) {
      const mid = (lo + hi) >> 1;
      if (row[mid].x > x) hi = mid;
      else lo = mid + 1;
    }
    for (let i = lo; i < row.length; i++) if (row[i] !== exclude) return row[i];
    return null;
  }

  /** Last vehicle in `lane` strictly before `x`, or null. */
  private lastBefore(lane: number, x: number, exclude?: Vehicle): Vehicle | null {
    const row = this.laneIndex[lane];
    if (!row || row.length === 0) return null;
    let lo = 0;
    let hi = row.length;
    while (lo < hi) {
      const mid = (lo + hi) >> 1;
      if (row[mid].x < x) lo = mid + 1;
      else hi = mid;
    }
    for (let i = lo - 1; i >= 0; i--) if (row[i] !== exclude) return row[i];
    return null;
  }
  private completedTimes: number[] = []; // travel times, rolling
  private completedInWindow: number[] = []; // completion timestamps, rolling
  private co2Window: { t: number; g: number }[] = [];
  private readonly warmupS: number;
  /** Ramps, sorted by position so a vehicle's exit can be picked in one pass. */
  private readonly ramps: RampSpec[];
  private rampAccumulator: number[] = [];
  /** Vehicles asked for, and vehicles actually let on, since the warm-up. */
  private demanded = 0;
  private admitted = 0;

  /** Class kinematics for THIS run: the defaults, with any warehouse values
   *  laid over them. Shares are renormalised so a partial override cannot make
   *  pickClass fall off the end of the distribution. */
  private readonly cls: Record<VehicleClass, { v0: number; len: number; co2PerM: number; color: string; share: number }>;

  constructor(cfg: SimConfig, interventions?: Partial<Interventions>) {
    this.cfg = cfg;
    {
      const base = { 1: { ...CLASS[1] }, 2: { ...CLASS[2] }, 3: { ...CLASS[3] } } as Record<
        VehicleClass,
        { v0: number; len: number; co2PerM: number; color: string; share: number }
      >;
      const over = cfg.classProfile;
      if (over) {
        for (const k of [1, 2, 3] as VehicleClass[]) {
          const o = over[k];
          if (!o) continue;
          if (typeof o.co2PerM === "number" && o.co2PerM > 0) base[k].co2PerM = o.co2PerM;
          if (typeof o.share === "number" && o.share >= 0) base[k].share = o.share;
        }
        const sum = base[1].share + base[2].share + base[3].share;
        if (sum > 0) for (const k of [1, 2, 3] as VehicleClass[]) base[k].share /= sum;
      }
      this.cls = base;
    }
    this.warmupS = cfg.warmupS ?? DEFAULT_WARMUP_S;
    // Sorted so pickExit can walk them in order and stop at the first one past
    // the vehicle; unsorted, a vehicle could be assigned an exit behind it.
    this.ramps = [...(cfg.ramps ?? [])].sort((a, b) => a.x - b.x);
    this.rampAccumulator = this.ramps.map(() => 0);
    this.rng = mulberry32(cfg.seed);
    this.interventions = {
      closedLanes: Array(cfg.laneCount).fill(false),
      closurePoint: cfg.length * 0.55,
      closureEnd: cfg.length,
      incidents: [],
      speedLimitKmh: null,
      speedZone: [cfg.length * 0.35, cfg.length * 0.75],
      ...interventions,
    };
    this.prefill();
  }

  /**
   * Put traffic on the road before the first step.
   *
   * Vehicles only ever enter at x = 0, so a freshly built simulation was an
   * empty carriageway that filled from the left at traffic speed: about 13
   * seconds for a 280 m stretch, 52 for a kilometre. Since changing the
   * segment, the lane count or the route rebuilds the simulation, an operator
   * adjusting any of those watched an empty road and reasonably concluded it
   * had broken.
   *
   * The road is seeded at the headway the configured inflow implies, so it
   * starts in roughly the state it would have converged to anyway. Interventions
   * are not applied here — a closure should be seen to cause its queue, not
   * begin with one — so a closed lane simply starts empty.
   */
  private prefill() {
    const lanes = this.cfg.laneCount;
    const openLanes = Array.from({ length: lanes }, (_, i) => i).filter(
      (i) => !this.interventions.closedLanes[i],
    );
    const { closurePoint: cFrom, closureEnd: cTo } = this.interventions;
    if (openLanes.length === 0) return;

    // Equilibrium headway: seconds between vehicles in one lane at this flow.
    const perLanePerSec = this.cfg.inflowVehPerHour / 3600 / openLanes.length;
    if (perLanePerSec <= 0) return;
    const headwaySec = 1 / perLanePerSec;

    for (const lane of openLanes) {
      // Stagger lanes so the seed does not read as a grid of rows.
      let x = this.cfg.length - this.rng() * headwaySec * 20;
      while (x > 0) {
        // A closed stretch starts empty even in an open lane's neighbour — a
        // vehicle seeded inside the works would be there before the closure
        // caused anything.
        if (this.interventions.closedLanes[lane] && x >= cFrom && x <= cTo) {
          x -= 10;
          continue;
        }
        // Lane 0 seeds light vehicles only. Chosen outright rather than drawn
        // and rejected: a reject-and-retry loop is unbounded in principle, and
        // the answer here is not a matter of chance.
        const vClass: VehicleClass = lane < HEAVY_MIN_LANE ? 1 : this.pickClass();
        const profile = this.pickProfile();
        const c = this.cls[vClass];
        const d = makeDriver(this.rng, vClass, profile);
        const v0 = d.v0;
        const v = v0 * (0.85 + 0.15 * this.rng());
        this.vehicles.push({
          id: this.nextId++,
          lane,
          x,
          v,
          vClass,
          profile,
          v0,
          T: d.T,
          aMax: d.aMax,
          politeness: d.politeness,
          lcSec: d.lcSec,
          scanSec: d.scanSec,
          scanTimer: d.scanTimer,
          patience: d.patience,
          stuckFor: 0,
          reactionS: d.reactionS,
          reactTimer: d.reactTimer,
          accel: 0,
          exitAtX: this.pickExit(0),
          length: c.len,
          // Negative so the first throughput readings are not skewed by a
          // cohort that appears to have crossed the segment instantly.
          spawnTime: -(this.cfg.length - x) / Math.max(1, v),
          co2: 0,
          laneCooldown: 0,
          laneFrom: lane,
          laneShift: 1,
          color: varyColor(c.color, this.rng()),
        });
        // Spacing from the headway, never closer than the car-following model
        // would tolerate.
        const gap = Math.max(v * headwaySec, c.len + S0 + 2);
        x -= gap * (0.85 + 0.3 * this.rng());
      }
    }
  }

  private pickClass(): VehicleClass {
    const r = this.rng();
    if (r < this.cls[1].share) return 1;
    if (r < this.cls[1].share + this.cls[2].share) return 2;
    return 3;
  }

  private pickProfile(): DriverProfile {
    const r = this.rng();
    return r < 0.25 ? "cautious" : r < 0.85 ? "normal" : "aggressive";
  }

  private spawn(lane: number, vClass: VehicleClass, exitAtX: number | null = null) {
    const profile = this.pickProfile();
    const c = this.cls[vClass];
    const d = makeDriver(this.rng, vClass, profile);

    /* Enter at the speed of the traffic already in the lane.
     *
     * Previously a fixed 0.6-0.9 of 22 m/s regardless of what was in front.
     * Joining a moving carriageway at an unrelated speed is not how traffic
     * enters a segment, and the mismatch was doing real damage downstream —
     * see the gap test below. */
    /* Scanned live, NOT through the lane index.
     *
     * The index is rebuilt once per step, so several spawns inside the same
     * tick would every one of them see the road as it was before any of them
     * arrived, and all pile onto x = 0 on top of each other. */
    let lead: Vehicle | null = null;
    for (const other of this.vehicles) {
      if (other.lane !== lane) continue;
      if (!lead || other.x < lead.x) lead = other;
    }
    const enterV = Math.min(d.v0, lead ? Math.max(lead.v, 4) : d.v0);

    /* Refuse unless the gap is one this vehicle could actually take.
     *
     * The old test was a fixed 11 m of clearance, which is a parking
     * distance, not a driving one. A car entering at 15 m/s into an 11 m gap
     * is 17 m inside its own safe headway, so IDM answered with about
     * -127 m/s², the vehicle emergency-stopped a few metres in, and it then
     * blocked the entrance for everyone behind it. That single line was
     * capping the whole model: measured capacity was ~1,100 veh/h/lane
     * against a real motorway's ~2,000, and above 1,200 veh/h/lane of demand
     * served flow COLLAPSED instead of saturating, with 978 vehicles quietly
     * queued in an accumulator that nothing ever drew.
     *
     * The requirement is the IDM equilibrium spacing at the entry speed —
     * exactly the gap the vehicle will settle at anyway — so a vehicle is
     * admitted only when the road in front of it can already support it. */
    const nearest = lead ? lead.x : Infinity;
    if (nearest < c.len + S0 + enterV * d.T) return false;

    this.vehicles.push({
      id: this.nextId++,
      lane,
      x: 0,
      v: enterV,
      vClass,
      profile,
      v0: d.v0,
      T: d.T,
      aMax: d.aMax,
      politeness: d.politeness,
      lcSec: d.lcSec,
      scanSec: d.scanSec,
      scanTimer: d.scanTimer,
      patience: d.patience,
      stuckFor: 0,
      reactionS: d.reactionS,
      reactTimer: d.reactTimer,
      accel: 0,
      exitAtX,
      length: c.len,
      spawnTime: this.time,
      co2: 0,
      laneCooldown: 0,
      laneFrom: lane,
      laneShift: 1,
      color: varyColor(c.color, this.rng()),
    });
    return true;
  }

  // Desired speed at a position, honouring an active speed-limit zone.
  private desiredSpeed(v: Vehicle): number {
    const { speedLimitKmh, speedZone } = this.interventions;
    let v0 = v.v0;
    if (speedLimitKmh != null && v.x >= speedZone[0] && v.x <= speedZone[1]) {
      v0 = Math.min(v0, speedLimitKmh / 3.6);
    }
    v0 *= this.mergeCaution(v);
    v0 *= this.exitCaution(v);
    return v0;
  }

  /** Speed factor for a driver running out of road before their exit.
   *
   *  Measured cause: of the drivers who missed their interchange, 47 of 68
   *  were sitting in the lane NEXT to the exit lane when they sailed past it.
   *  They were not lost, and they were not being refused by the bias — they
   *  simply never found a gap, because the outer lane is the busiest one and
   *  they were travelling at the same speed as it. Two vehicles side by side
   *  at the same speed never produce a gap between them.
   *
   *  What a real driver does is lift off and slot in behind someone. Easing
   *  their desired speed does exactly that through the existing car-following:
   *  they drop back, a gap opens alongside, and the lane-change decision that
   *  was already trying to fire finally passes its safety test.
   *
   *  It also produces the weaving slowdown around interchanges, which is a
   *  real effect and the main reason a junction is a bottleneck rather than
   *  just a place where vehicles are added and removed. */
  private exitCaution(v: Vehicle): number {
    if (v.exitAtX == null) return 1;
    if (v.lane === this.exitLane) return 1; // already in the right place
    const toGo = v.exitAtX - v.x;
    if (toGo < 0 || toGo > EXIT_COMMIT_M) return 1;
    const pressure = 1 - toGo / EXIT_COMMIT_M;
    return 1 - (1 - EXIT_CAUTION) * pressure;
  }

  /** Speed factor for a driver approaching someone else's lane drop.
   *
   *  Applies in the OPEN lanes next to a closure, over the same merge zone the
   *  merging traffic uses, ramping from 1 far upstream to MERGE_CAUTION at the
   *  taper. The vehicle in the closed lane is not slowed here — it already has
   *  the taper itself as a stopped obstacle, and doubling that up would brake
   *  it twice for the same thing.
   *
   *  Because this slows the receiving lane, its own followers slow in turn, so
   *  the disturbance propagates outward and upstream through ordinary
   *  car-following rather than being painted on lane by lane. */
  private mergeCaution(v: Vehicle): number {
    const { closedLanes, closurePoint, closureEnd } = this.interventions;
    if (v.x > closurePoint || v.x > closureEnd) return 1;
    if (closedLanes[v.lane]) return 1; // the taper already governs this one
    const adjacentClosed =
      Boolean(closedLanes[v.lane - 1]) || Boolean(closedLanes[v.lane + 1]);
    if (!adjacentClosed) return 1;
    const urgency = Math.max(0, Math.min(1, 1 - (closurePoint - v.x) / MERGE_ZONE_M));
    return 1 - (1 - MERGE_CAUTION) * urgency;
  }

  // Gap + relative speed to whatever is ahead in a given lane: real leader,
  // an incident, or a lane-closure taper. Returns null if the road is clear.
  private leaderAhead(v: Vehicle, lane: number): { gap: number; dv: number } | null {
    // `x` is the front bumper; track the front of the nearest thing ahead
    // (`bestX`) and its length (`leadLen`) so the bumper-to-bumper gap is
    // measured to the leader's REAR — not miscounted through our own body.
    let bestX = Infinity;
    let leadV = 0;
    let leadLen = 0;
    // real vehicles — nearest ahead, from the per-lane index
    {
      const o = this.firstAfter(lane, v.x, v);
      if (o) {
        bestX = o.x;
        leadV = o.v;
        leadLen = o.length;
      }
    }
    // incidents (stopped obstacles) in this lane
    for (const inc of this.interventions.incidents) {
      if (inc.lane === lane && inc.x > v.x && inc.x < bestX) {
        bestX = inc.x;
        leadV = 0;
        leadLen = INCIDENT_LENGTH;
      }
    }
    // A closure acts as a stopped obstacle at its taper — but only for traffic
    // that has not already passed the far end. Without the second test a
    // vehicle that has cleared the works still braked for a barrier behind it.
    if (
      this.interventions.closedLanes[lane] &&
      v.x < this.interventions.closureEnd &&
      this.interventions.closurePoint > v.x &&
      this.interventions.closurePoint < bestX
    ) {
      bestX = this.interventions.closurePoint;
      leadV = 0;
      leadLen = 0;
    }
    if (!isFinite(bestX)) return null;
    const gap = bestX - v.x - leadLen;
    return { gap: Math.max(0.1, gap), dv: v.v - leadV };
  }

  private idmAccel(v: Vehicle, lane: number): number {
    // v.aMax / v.T, not the profile's. Reading the shared table here was what
    // collapsed nine hundred drivers into nine behaviours no matter what was
    // stored on the vehicle.
    const v0 = this.desiredSpeed(v);
    const free = v.aMax * (1 - Math.pow(v.v / Math.max(1, v0), DELTA));
    const lead = this.leaderAhead(v, lane);
    if (!lead) return free;
    const sStar = S0 + Math.max(0, v.v * v.T + (v.v * lead.dv) / (2 * Math.sqrt(v.aMax * B_COMF)));
    const interaction = -v.aMax * Math.pow(sStar / lead.gap, 2);
    return free + interaction;
  }

  // Would merging a vehicle of `length` at front-position `x` land it on top of
  // (or right up against) a stalled incident in `lane`? Used to stop cars from
  // changing lanes directly onto an accident.
  private incidentTooCloseInLane(lane: number, x: number, length: number): boolean {
    for (const inc of this.interventions.incidents) {
      if (inc.lane !== lane) continue;
      const incFront = inc.x;
      const incRear = inc.x - INCIDENT_LENGTH;
      // the vehicle would occupy [x - length, x]; require an S0 buffer each side
      if (incFront > x - length - S0 && incRear < x + S0) return true;
    }
    return false;
  }

  // MOBIL-ish lane change: pick the neighbouring lane that is safe and offers a
  // meaningfully better acceleration, with a strong pull out of a blocked lane.
  private considerLaneChange(v: Vehicle) {
    if (v.laneCooldown > 0) return;
    // Belt and braces: the cooldown already outlasts the slide, but a vehicle
    // still visibly straddling a line must not be re-aimed at a third lane,
    // whatever the cooldown says.
    if (v.laneShift < 1) return;
    const here = this.idmAccel(v, v.lane);
    // Blocked for THIS vehicle only while it is upstream of the works.
    const blockedFor = (lane: number) =>
      this.interventions.closedLanes[lane] && v.x < this.interventions.closureEnd;
    const mustEscape = blockedFor(v.lane) && v.x < this.interventions.closurePoint;
    let candidates = [v.lane - 1, v.lane + 1].filter(
      (l) => l >= 0 && l < this.cfg.laneCount && !blockedFor(l),
    );
    /* Keep buses and trucks out of the inner lane.
     *
     * The exception is a heavy vehicle that has to leave a lane closing ahead
     * of it and has nowhere legal to go. Held to the restriction there, it
     * would stop dead at the taper and hold up everything queued behind it for
     * the rest of the run — the restriction would read on screen as a bug in
     * the closure. Roadworks lift lane restrictions for exactly this reason.
     *
     * "Nowhere to go" originally meant no permitted lane EXISTS, which is the
     * wrong test and left the bug in place: a bus in a closed L2 has L3
     * permitted, so the exception never fired, and if L3 was full the bus
     * parked at the taper anyway. Measured on a 4-lane run with L2 shut, the
     * stationary queue at the taper was entirely class 2 for this reason.
     *
     * So the test is now whether the vehicle has actually run out of road: its
     * lane is closing AND it has come to a stop. A moving vehicle still
     * upstream keeps looking for a legal gap; only one that has already failed
     * to find one may take the restricted lane, and the penalty further down
     * means it still prefers a permitted lane whenever one will have it. */
    const permitted = candidates.filter((l) => laneAllowsClass(v.vClass, l));
    const desperate = mustEscape && v.v < CREEP_SPEED;
    if (!mustEscape || (permitted.length > 0 && !desperate)) candidates = permitted;

    /* How badly this vehicle needs the gap: 0 far upstream of the taper, 1 at
     * it. Drives both how hard it may push the new follower and how strongly
     * the escape outweighs staying put, so the merge is polite while there is
     * road left and insistent once there is not. */
    const urgency = mustEscape
      ? Math.max(0, Math.min(1, 1 - (this.interventions.closurePoint - v.x) / MERGE_ZONE_M))
      : 0;

    /* Working across for an exit.
     *
     * A driver leaving at the next interchange is not choosing a lane on
     * comfort, they are getting to the outside before the ramp arrives, and
     * they start well before it. Without this the ramps would drain only
     * whoever happened to be in the outer lane already, and the weaving that
     * makes interchanges the real bottleneck on this corridor would never
     * appear. */
    const toExit = v.exitAtX != null ? v.exitAtX - v.x : Infinity;
    const exiting = toExit <= EXIT_APPROACH_M;
    const exitUrgency = exiting
      ? Math.max(0, Math.min(1, 1 - toExit / EXIT_APPROACH_M))
      : 0;
    /* Pressure in the last stretch before a ramp.
     *
     * The outward bias alone only tells a driver which way to go; it does not
     * let them take a gap a comfortable driver would decline, and near the
     * ramp that is the binding constraint — 43% of drivers were still
     * sailing past their exit because every gap on offer failed the ordinary
     * safety test. A driver 50 m from the exit they need takes a tighter gap
     * than one cruising, exactly as at a closure taper, so the same easing
     * applies. Sharper than the approach bias: only the final 150 m. */
    const exitPressure =
      v.exitAtX != null
        ? Math.max(0, Math.min(1, 1 - (v.exitAtX - v.x) / EXIT_COMMIT_M))
        : 0;
    const bSafeEff = B_SAFE + Math.max(urgency, exitPressure) * (B_SAFE_FORCED - B_SAFE);
    let best: { lane: number; gain: number } | null = null;
    for (const lane of candidates) {
      // never change lanes onto (or right up against) an accident
      if (this.incidentTooCloseInLane(lane, v.x, v.length)) continue;
      // safety: would the new follower have to brake harder than B_SAFE?
      const follower = this.lastBefore(lane, v.x, v);
      const lead = this.firstAfter(lane, v.x, v);
      const roomAhead = lead ? lead.x - v.x - lead.length : Infinity;
      /* Gap between this vehicle's rear and the follower's nose.
       *
       * This subtracted the FOLLOWER's length instead of the merging
       * vehicle's. Harmless when a car merged ahead of a truck (it just
       * understated the gap and refused a few legal moves) but wrong the
       * other way: a 14 m truck merging ahead of a 4.6 m car was checked as
       * though it were 4.6 m long, so it could drop its tail straight through
       * the car behind. */
      const gapBehind = follower ? v.x - v.length - follower.x : Infinity;

      /* Out of patience: nose in and make the follower yield.
       *
       * Judged on whether the follower has room to brake, not on whether the
       * braking would be comfortable — that is the whole point of forcing.
       * Still refuses a gap that is not physically there, so this never
       * teleports a vehicle into an occupied space. */
      const forcing =
        mustEscape &&
        v.stuckFor > v.patience &&
        roomAhead >= CREEP_GAP &&
        gapBehind >= Math.max(S0, (follower?.v ?? 0) * FORCE_TTC_SEC);

      /* Zipper merge at crawling pace.
       *
       * The IDM veto below asks "how hard would the new follower have to
       * brake?", and the gain test asks "would I accelerate better over
       * there?". In a jam neither question has a useful answer: gaps are a few
       * metres, so sStar/gap explodes and both the implied deceleration and
       * the implied gain are enormous even when everyone involved is nearly
       * stopped and letting one vehicle in costs nothing. The tests therefore
       * bite hardest exactly where merging matters most.
       *
       * Measured over five 10-minute runs with L2 shut, about 2.7 vehicles sat
       * parked at the taper at any moment and the worst stayed six minutes,
       * blocking its lane for the rest of the run. On the canvas that reads as
       * the closure having broken the simulation, which is what it was
       * reported as.
       *
       * A driver at a taper does not compute a deceleration. They creep to the
       * head of the queue, nose in, and the driver behind yields. So below
       * walking pace the test becomes the one a driver actually makes: is
       * there physically room? */
      const creeping =
        mustEscape &&
        v.v < CREEP_SPEED &&
        (!follower || follower.v < CREEP_SPEED) &&
        roomAhead >= CREEP_GAP;

      /* Physical fit. Checked for every change, not just a forced one.
       *
       * Nothing else enforced it: the follower had a gap test but the LEADER
       * had none, and the only thing discouraging a move into an occupied
       * space was the IDM gain being poor there — which the escape bias can
       * outweigh. The result was two sprites drawn through each other, up to a
       * full 14 m artic inside another vehicle. A gain term is not a substitute
       * for asking whether the car fits. */
      if (roomAhead < (creeping || forcing ? CREEP_GAP : S0)) continue;
      /* What the move costs the driver being cut in front of.
       *
       * MOBIL's defining term, and it was missing: `politeness` was defined on
       * every profile and read by nothing, so the decision was pure self
       * interest and an aggressive driver changed lanes on exactly the same
       * evidence as a cautious one. The only thing separating them was the
       * safety veto below, which is a hard limit rather than a temperament.
       *
       * Now the disadvantage inflicted on the new follower is weighed at this
       * driver's own politeness: near 0 they take any gap that helps them, near
       * 0.85 they hold station rather than force someone to lift off. */
      let courtesy = 0;
      if (follower) {
        if (gapBehind < S0) continue;
        const followerAccel = this.idmAccelAgainst(follower, v.x, v.v, v.length);
        if (!creeping && !forcing && followerAccel < -bSafeEff) continue;
        /* Politeness applies to a DISCRETIONARY change only.
         *
         * A vehicle whose own lane is closing ahead is making a mandatory
         * move: the alternative is not "stay and be slightly slower", it is
         * "stop at the taper". Charging it the follower's inconvenience made
         * merging impossible in exactly the traffic where merging matters —
         * in a queue the follower's disadvantage runs well past the 3.0 escape
         * bias, so the term cancelled the bias and cars sat in the closed lane
         * until the run ended, which on screen looked like the closure had
         * broken the simulation rather than like courtesy.
         *
         * The safety veto above still applies while there is speed in the
         * queue, so a mandatory merge at pace can never force anyone to brake
         * harder than B_SAFE. Once everyone is crawling it gives way to the
         * physical-room test instead — see `creeping`. */
        // Committed to an exit is as mandatory as escaping a closure: the
        // alternative is not "slightly slower", it is missing the junction.
        if (!mustEscape && exitPressure < 0.5) {
          const followerNow = this.idmAccel(follower, lane);
          courtesy = v.politeness * (followerNow - followerAccel);
        }
      }
      const there = this.idmAccel(v, lane);
      let gain = there - here - courtesy;
      /* Keep right except to overtake. Outward is rewarded, inward charged,
       * so the inner lane is only worth taking when there is real time in it.
       * Suspended while escaping a closure — a vehicle merging out of a shut
       * lane is not choosing a cruising lane, and charging it for moving
       * inward would send it the wrong way or nowhere at all. */
      if (!mustEscape) {
        gain += lane > v.lane ? LANE_DISCIPLINE : -LANE_DISCIPLINE;
      }
      // Scaled by the same urgency: a distant closure is a nudge, the taper is
      // an order. Without the floor a vehicle 150 m out would ignore the closure
      // entirely and only react once already slowing for it.
      if (mustEscape) gain += LC_BIAS_ESCAPE * (0.4 + 0.6 * urgency);
      // Outward towards the ramp, and charged for going the wrong way.
      if (exiting && lane !== v.lane) {
        const pull = LC_BIAS_EXIT * (0.3 + 0.7 * exitUrgency);
        gain += lane > v.lane ? pull : -pull;
      }
      /* At crawling pace the acceleration comparison is noise: every lane
       * scores terribly because every gap is small, so `gain` cannot separate
       * a lane with room from one without. Score by room instead — which is
       * what the driver is actually looking at — and keep it above
       * LC_THRESHOLD so a vehicle with somewhere to go always goes. The cap
       * stops a long empty stretch from outweighing a nearer, safer gap. */
      if (creeping || forcing) gain = LC_BIAS_ESCAPE + Math.min(10, roomAhead);
      /* Committed to an exit, and this is the lane it is on.
       *
       * The acceleration comparison cannot decide this. The outer lane is the
       * busiest one, so IDM scores it at around -5 m/s², and no bias of a
       * plausible size outvotes that — which is why 40% of drivers were still
       * sailing past their junction even once the bias, the safety easing and
       * the speed easing were all in place. Every one of those tests was
       * passing; the gain test was throwing the move away afterwards.
       *
       * A driver about to miss their exit is not weighing acceleration. They
       * take the gap if it exists, and the cost of arriving in a slower lane
       * does not enter into it. Physical room is still required. */
      if (
        exitPressure > 0.5 &&
        lane === this.exitLane &&
        roomAhead >= S0 &&
        gapBehind >= S0
      ) {
        gain = Math.max(gain, LC_THRESHOLD + 0.1 + Math.min(10, roomAhead) * 0.05);
      }
      /* A heavy vehicle taking a lane it is normally barred from is breaking a
       * rule to avoid blocking the road. Charged for it, so that whenever a
       * permitted lane will also have it, the permitted lane wins. */
      if (!laneAllowsClass(v.vClass, lane)) gain -= RESTRICTED_LANE_PENALTY;
      if (gain > LC_THRESHOLD && (!best || gain > best.gain)) best = { lane, gain };
    }
    if (best) {
      // Start the slide from wherever the sprite currently is, not from the
      // lane being left. They are the same thing for a settled vehicle, and
      // differ only if a change is somehow accepted mid-manoeuvre — in which
      // case continuing from the drawn position is what avoids a jump.
      v.laneFrom = visualLane(v);
      v.laneShift = 0;
      v.lane = best.lane;
      v.laneCooldown = v.lcSec + LC_SETTLE_SEC;
    }
  }

  // IDM accel of `f` if a vehicle were at position `leadX` moving `leadV`.
  private idmAccelAgainst(f: Vehicle, leadX: number, leadV: number, leadLen: number): number {
    const v0 = this.desiredSpeed(f);
    const free = f.aMax * (1 - Math.pow(f.v / Math.max(1, v0), DELTA));
    const gap = Math.max(0.1, leadX - f.x - leadLen);
    const dv = f.v - leadV;
    const sStar = S0 + Math.max(0, f.v * f.T + (f.v * dv) / (2 * Math.sqrt(f.aMax * B_COMF)));
    return free - f.aMax * Math.pow(sStar / gap, 2);
  }

  private emit(v: Vehicle, dist: number, dt: number) {
    const base = this.cls[v.vClass].co2PerM;
    const vKmh = v.v * 3.6;
    // congestion penalty: crawling burns far more per metre; idling still emits
    const congestion = 1 + Math.max(0, (30 - vKmh) / 30) * 1.2;
    const moving = base * dist * congestion;
    const idle = v.v < 0.5 ? this.cls[v.vClass].co2PerM * 6 * dt : 0; // g while stopped
    const g = moving + idle;
    v.co2 += g;
    this.co2Window.push({ t: this.time, g });
  }

  // Nearest impassable point ahead of `fromX` in a lane: the rear of a stalled
  // incident, or a closed lane's taper. Infinity if the lane is clear ahead.
  private blockPointAhead(lane: number, fromX: number): number {
    let wall = Infinity;
    for (const inc of this.interventions.incidents) {
      if (inc.lane !== lane) continue;
      const rear = inc.x - INCIDENT_LENGTH;
      if (rear >= fromX && rear < wall) wall = rear;
    }
    if (this.interventions.closedLanes[lane]) {
      const cp = this.interventions.closurePoint;
      // Only a wall to traffic that still has to get past the works.
      if (fromX < this.interventions.closureEnd && cp >= fromX && cp < wall) wall = cp;
    }
    return wall;
  }

  /* Which interchange, if any, this vehicle intends to leave by.
   *
   * Decided once at entry rather than re-rolled as it drives, because a
   * driver knows where they are going. Each downstream ramp gets its
   * `offFraction` share of whatever traffic is still on the road by then,
   * which is how turning proportions compose along a corridor: 20% leaving at
   * two successive ramps takes 20% then 20% of the remaining 80%, not 40%. */
  private pickExit(fromX: number): number | null {
    for (const r of this.ramps) {
      if (r.x <= fromX + 1) continue; // already passed it
      if (r.offFraction > 0 && this.rng() < r.offFraction) return r.x;
    }
    return null;
  }

  /** The lane a vehicle must be in to use a ramp: the outermost one. */
  private get exitLane(): number {
    return this.cfg.laneCount - 1;
  }

  /* Traffic joining at the on-ramps.
   *
   * Joins in the outermost lane at the ramp's own position, at a speed typical
   * of an acceleration lane rather than at free flow — a vehicle appearing at
   * 100 km/h in the middle of the carriageway would be both wrong and
   * invisible as a disturbance. Merging traffic entering below the prevailing
   * speed is precisely what makes an interchange a bottleneck. */
  private spawnFromRamps(dt: number) {
    for (let i = 0; i < this.ramps.length; i++) {
      const r = this.ramps[i];
      if (r.onVehPerHour <= 0) continue;
      this.rampAccumulator[i] += (r.onVehPerHour / 3600) * dt;
      while (this.rampAccumulator[i] >= 1) {
        this.rampAccumulator[i] -= 1;
        const lane = this.exitLane;
        const vClass = this.pickClass();
        const c = this.cls[vClass];
        const profile = this.pickProfile();
        const d = makeDriver(this.rng, vClass, profile);

        /* Scanned live, not through the lane index, for the same reason the
         * mainline spawn is: the index is a step old and several joins can
         * happen inside one step. */
        let ahead: Vehicle | null = null;
        let behind: Vehicle | null = null;
        for (const other of this.vehicles) {
          if (other.lane !== lane) continue;
          if (other.x >= r.x) { if (!ahead || other.x < ahead.x) ahead = other; }
          else if (!behind || other.x > behind.x) behind = other;
        }
        const joinV = Math.min(
          d.v0,
          ahead ? Math.max(ahead.v, 4) : d.v0,
          RAMP_JOIN_SPEED * gauss(this.rng, 0.15, 0.6, 1.4),
        );
        /* Same dynamic test as the mainline entrance: room for the vehicle it
         * will become, at the speed it will be doing. A joiner that cannot fit
         * waits on the ramp — and its place in the queue is KEPT rather than
         * discarded, which is what was quietly losing 40% of every ramp's
         * configured volume. */
        const needAhead = c.len + S0 + joinV * d.T;
        const needBehind = behind ? S0 + behind.v * 0.8 : S0;
        if ((ahead && ahead.x - ahead.length - r.x < needAhead - c.len) ||
            (behind && r.x - c.len - behind.x < needBehind)) {
          this.rampAccumulator[i] = Math.min(this.rampAccumulator[i] + 1, MAX_ENTRY_QUEUE);
          break;
        }
        this.vehicles.push({
          id: this.nextId++,
          x: r.x, lane, v: Math.max(4, joinV), vClass, profile,
          v0: d.v0, T: d.T, aMax: d.aMax, politeness: d.politeness, lcSec: d.lcSec,
          scanSec: d.scanSec, scanTimer: d.scanTimer, patience: d.patience, stuckFor: 0,
          reactionS: d.reactionS, reactTimer: d.reactTimer, accel: 0,
          exitAtX: this.pickExit(r.x),
          length: c.len, spawnTime: this.time, co2: 0,
          laneCooldown: 0, laneFrom: lane, laneShift: 1,
          color: varyColor(c.color, this.rng()),
        });
      }
    }
  }

  /* Vehicles peeling off at their interchange.
   *
   * Removed once they reach the ramp, but only from the outermost lane — a
   * vehicle that failed to work its way across in time misses its exit and
   * carries on, which is both what happens and what keeps the exit lane's
   * demand honest. Getting there is handled by the lane-change bias. */
  private takeExits() {
    if (this.ramps.length === 0) return;
    this.vehicles = this.vehicles.filter((v) => {
      if (v.exitAtX == null || v.x < v.exitAtX) return true;
      if (v.lane !== this.exitLane) {
        // Missed it. Carry on to the next one they can reach, or run through.
        v.exitAtX = this.pickExit(v.x);
        return true;
      }
      this.completedTimes.push(this.time - v.spawnTime);
      this.completedInWindow.push(this.time);
      return false;
    });
  }

  // Place a stalled-vehicle incident. Any car sitting on that spot is absorbed
  // into the accident (removed) so nothing appears to drive out of it.
  addIncident(lane: number, x: number) {
    const front = x + 1;
    const rear = x - INCIDENT_LENGTH - 1;
    this.vehicles = this.vehicles.filter(
      (v) => v.lane !== lane || v.x - v.length >= front || v.x <= rear
    );
    this.interventions.incidents.push({ lane, x });
  }

  step(dt: number) {
    const before = this.time;
    this.time += dt;
    /* Discard everything collected during the warm-up.
     *
     * The rolling windows alone are not enough: at the instant the warm-up
     * ends they still hold the previous 60 s, which is exactly the filling
     * transient the warm-up exists to exclude. Clearing them here means the
     * first warm reading is built only from warm data. */
    if (before < this.warmupS && this.time >= this.warmupS) {
      this.completedInWindow = [];
      this.completedTimes = [];
      this.co2Window = [];
      this.demanded = 0;
      this.admitted = 0;
    }
    // Every lookup below reads this; it must reflect the positions the
    // decisions are made against, so it is built before any of them.
    this.rebuildLaneIndex();

    // Inflow across ALL lanes — a lane closure is a downstream work zone, so
    // vehicles still enter the closing lane and must merge out at the taper.
    // That zipper merge is what makes congestion emerge on a closure.
    this.demanded += (this.cfg.inflowVehPerHour / 3600) * dt;
    this.spawnAccumulator += (this.cfg.inflowVehPerHour / 3600) * dt;
    while (this.spawnAccumulator >= 1) {
      this.spawnAccumulator -= 1;
      // Class first, then a lane that class is allowed in. Picking the lane
      // first and downgrading anything heavy that landed in L1 would quietly
      // delete a quarter of the buses and trucks from the whole run; choosing
      // among the legal lanes instead keeps the fleet mix exactly as
      // configured and simply spreads the heavies over the lanes they may use.
      const vClass = this.pickClass();
      /* Destination first, because it decides which lane they join in.
       *
       * Assigning a random lane and then asking the driver to cross the
       * carriageway is what a driver would never do: someone leaving at the
       * next interchange joins near the outside. Spawned at random instead,
       * 66% of them missed their exit and were silently re-assigned to a
       * later one, so the ramps drained at a third of the turning proportion
       * they were configured with. */
      const exitAtX = this.pickExit(0);
      const legal: number[] = [];
      for (let l = 0; l < this.cfg.laneCount; l++) if (laneAllowsClass(vClass, l)) legal.push(l);
      // A one-lane road is all inner lane; there is nowhere legal to put a
      // truck, and refusing to spawn it would silently drop freight instead.
      if (legal.length === 0) legal.push(0);

      /* Try every lane the class may use, not just one at random.
       *
       * A spawn is refused when the entrance of that lane is still occupied,
       * and the vehicle was then simply discarded. That is not neutral: the
       * check is `nearest < length + gap`, so a 14 m truck is refused in
       * conditions a 4.6 m car passes, and the longer the vehicle the more
       * often it is dropped. The fleet on the road therefore drifted light no
       * matter what share was configured — measured at 5.6% Class 3 against
       * the 8.9% asked for.
       *
       * Shuffle so no lane is favoured, try them all, and if the whole
       * entrance is blocked give the credit back rather than destroying the
       * vehicle: the road is full, so the arrival is delayed, not cancelled. */
      for (let i = legal.length - 1; i > 0; i--) {
        const j = Math.floor(this.rng() * (i + 1));
        [legal[i], legal[j]] = [legal[j], legal[i]];
      }
      let placed = false;
      /* Someone leaving soon joins towards the outside; everyone else takes
       * whichever lane the shuffle offers. The shuffle above still applies
       * within each group, so no single lane is favoured. */
      if (exitAtX != null && exitAtX < EXIT_APPROACH_M * 1.5) legal.sort((a, b) => b - a);
      for (const lane of legal) {
        if (this.spawn(lane, vClass, exitAtX)) { placed = true; this.admitted++; break; }
      }
      if (!placed) {
        this.spawnAccumulator += 1; // retry on a later tick
        /* Cap the backlog. Left uncapped it reached 978 vehicles in a
         * 10-minute run — a phantom queue that nothing rendered, that no
         * metric reported, and that would have flooded the road the moment
         * demand eased. Past a few vehicles this is not traffic waiting to
         * enter, it is demand the segment cannot serve, and it is counted as
         * such rather than stored. */
        if (this.spawnAccumulator > MAX_ENTRY_QUEUE) this.spawnAccumulator = MAX_ENTRY_QUEUE;
        break; // entrance is full this step; stop trying
      }
    }

    // Traffic joining at the interchanges. After the mainline spawn, and the
    // index is rebuilt because both of them add vehicles the decisions below
    // have to see.
    if (this.ramps.length > 0) {
      this.spawnFromRamps(dt);
      this.rebuildLaneIndex();
    }

    // Lane-change decisions (before motion, using current state).
    for (const v of this.vehicles) {
      v.laneCooldown = Math.max(0, v.laneCooldown - dt);
      // Advance any slide already running before this step can start a new one,
      // so a manoeuvre always gets its full crossing time on screen.
      if (v.laneShift < 1) v.laneShift = Math.min(1, v.laneShift + dt / v.lcSec);
      /* Each driver decides on their own cadence, not on the simulation's. A
       * driver whose lane is closing ahead of them is watching far more
       * closely, so their clock runs faster. */
      const alert =
        this.interventions.closedLanes[v.lane] && v.x < this.interventions.closureEnd;
      // Patience runs down only while actually stuck: stopped, in a lane that
      // is closing. Any progress at all resets it.
      if (alert && v.v < CREEP_SPEED) v.stuckFor += dt;
      else v.stuckFor = 0;
      v.scanTimer -= alert ? dt * SCAN_ALERT_FACTOR : dt;
      if (v.scanTimer <= 0) {
        v.scanTimer = v.scanSec;
        this.considerLaneChange(v);
      }
    }

    // Longitudinal update (ballistic integration, clamped to >= 0).
    for (const v of this.vehicles) {
      const oldX = v.x;
      // Clamp to THIS driver's acceleration. Against the global A_MAX, every
      // driver drawn above average simply had the difference clipped off here,
      // quietly handing back the spread the traits were added to create.
      /* Recompute only when this driver's reaction time is up; otherwise keep
       * holding the acceleration they last chose. This is the lag: for up to
       * `reactionS` they are acting on a road that has already changed. */
      v.reactTimer -= dt;
      if (v.reactTimer <= 0) {
        v.reactTimer = v.reactionS;
        v.accel = this.idmAccel(v, v.lane);
      }
      const a = Math.max(-8, Math.min(v.aMax, v.accel));
      const vNew = Math.max(0, v.v + a * dt);
      v.x += Math.max(0, (v.v + vNew) / 2 * dt);
      v.v = vNew;
      // Safety net: a discrete step can carry a fast car *past* a stalled
      // obstacle the IDM couldn't brake for in time. Never let a car drive
      // out the far side of an accident (or closed-lane taper) — it stops
      // against it instead.
      const wall = this.blockPointAhead(v.lane, oldX);
      if (v.x > wall) {
        /* Stop against the obstacle — but behind anything already stopped
         * against it. Clamping straight to `wall` put every queued vehicle at
         * the identical coordinate, so a truck and a car ended up drawn on top
         * of one another at the taper (measured: 0.4% of ticks, worst overlap
         * 13.8 m, which is a whole articulated lorry inside a hatchback). */
        const ahead = this.firstAfter(v.lane, oldX, v);
        const limit = ahead ? Math.min(wall, ahead.x - ahead.length - S0) : wall;
        // Never below oldX: this is a brake, not a reversing manoeuvre.
        v.x = Math.max(oldX, Math.min(v.x, limit));
        v.v = 0;
      }
      this.emit(v, Math.max(0, v.x - oldX), dt);
    }

    /* Overlap safety net.
     *
     * IDM braking is capped at -8 m/s² and integrated in 0.05 s steps, so a
     * follower behind a vehicle that stops instantly — one clamped at a
     * taper, or an incident dropped in front of it — can penetrate it before
     * it has slowed. Two sprites drawn through each other is the most
     * obviously wrong thing this canvas can show, and it was happening on
     * 1.8% of ticks with a worst case of 8 m.
     *
     * So positions are corrected after the fact: nobody may occupy the space
     * inside the vehicle ahead. Leaders first, so one pass propagates a
     * correction back down the queue. The clearance is deliberately far
     * smaller than S0 — this is an anti-overlap floor, not a headway rule,
     * and using S0 here would forcibly space out legitimate jams and change
     * the flow it is supposed to be rendering. */
    for (let l = 0; l < this.cfg.laneCount; l++) {
      const row = this.vehicles.filter((v) => v.lane === l).sort((a, b) => b.x - a.x);
      for (let i = 1; i < row.length; i++) {
        const lead = row[i - 1];
        const me = row[i];
        const maxX = lead.x - lead.length - MIN_CLEARANCE;
        /* Never behind the entrance line. A vehicle pushed to negative x is
         * off the road: invisible, immobile, and still counted in density.
         * Measured at 925,052 vehicle-ticks in an oversaturated run, which is
         * what made density read 301/km/lane — above the physical jam
         * maximum — while the visible road looked half empty. Traffic that
         * cannot fit is refused at the entrance instead; see spawn(). */
        if (me.x > maxX) {
          me.x = Math.max(0, maxX);
          me.v = Math.min(me.v, lead.v); // stop pushing into it
        }
      }
    }

    // Vehicles peeling off at their interchange.
    this.takeExits();

    // Retire vehicles that cleared the segment; record travel time.
    const remaining: Vehicle[] = [];
    for (const v of this.vehicles) {
      if (v.x >= this.cfg.length) {
        this.completedTimes.push(this.time - v.spawnTime);
        this.completedInWindow.push(this.time);
      } else remaining.push(v);
    }
    this.vehicles = remaining;

    // Trim rolling windows (keep ~60 s / last 40 completions).
    const cutoff = this.time - 60;
    this.completedInWindow = this.completedInWindow.filter((t) => t >= cutoff);
    this.co2Window = this.co2Window.filter((e) => e.t >= this.time - 5);
    if (this.completedTimes.length > 40) this.completedTimes = this.completedTimes.slice(-40);
  }

  metrics(): Metrics {
    const n = this.vehicles.length;
    const avgV = n ? this.vehicles.reduce((s, v) => s + v.v, 0) / n : 0;
    const stopped = this.vehicles.filter((v) => v.v < 1).length;

    // longest standing queue (contiguous slow vehicles, any lane), in metres
    let longestQueue = 0;
    for (let l = 0; l < this.cfg.laneCount; l++) {
      const slow = this.vehicles
        .filter((v) => v.lane === l && v.v < 3)
        .sort((a, b) => a.x - b.x);
      let runStart: number | null = null;
      let prev: number | null = null;
      for (const v of slow) {
        if (prev == null || v.x - prev < 25) {
          if (runStart == null) runStart = v.x;
          prev = v.x;
        } else {
          longestQueue = Math.max(longestQueue, prev - (runStart ?? prev));
          runStart = v.x;
          prev = v.x;
        }
      }
      if (runStart != null && prev != null) longestQueue = Math.max(longestQueue, prev - runStart);
    }

    /* Measure from the end of the warm-up, not from t=0.
     *
     * The rolling windows already age old samples out, but the DENOMINATOR was
     * wrong during the transient: dividing by elapsed time while the road was
     * still filling counted an empty minute as if traffic had been flowing
     * through it, which understates throughput and makes the first reading a
     * scenario nobody chose. */
    const warm = this.time >= this.warmupS;
    const since = Math.max(1, this.time - (warm ? this.warmupS : 0));
    const windowSpanMin = Math.min(60, since) / 60;
    const throughput = this.completedInWindow.length / windowSpanMin;
    const co2g = this.co2Window.reduce((s, e) => s + e.g, 0);
    const co2Span = Math.min(5, Math.max(0.5, since));
    const co2RatePerMin = (co2g / co2Span) * 60 / 1000; // kg/min
    const avgTT = this.completedTimes.length
      ? this.completedTimes.reduce((s, t) => s + t, 0) / this.completedTimes.length
      : 0;

    return {
      activeAgents: n,
      avgSpeedKmh: avgV * 3.6,
      throughputPerMin: throughput,
      densityPerKmLane: (n / (this.cfg.length / 1000)) / this.cfg.laneCount,
      stoppedCount: stopped,
      longestQueueM: longestQueue,
      co2RatePerMin,
      avgTravelTimeS: avgTT,
      completed: this.completedInWindow.length,
      elapsedS: this.time,
      warm,
      unmetVehPerHour: Math.max(0, (this.demanded - this.admitted) / since) * 3600,
    };
  }
}

export const CLASS_META = CLASS;

/* ───────────────────────────────────────────────────────────────────────────
 * Replications
 *
 * A single run of a stochastic model is one sample, not an answer. The sandbox
 * animates one seed because that is what a sandbox is for, but any number an
 * operator is going to ACT on — "this closure costs 18% of throughput" — has
 * to come with an idea of how much of that 18% is the closure and how much is
 * the particular set of drivers this seed happened to generate.
 *
 * So the same scenario is run several times on different seeds and reported as
 * a mean with a confidence interval. If the interval straddles zero, the
 * difference is not evidence of anything.
 * ------------------------------------------------------------------------ */

export type RepStat = {
  mean: number;
  sd: number;
  /** Half-width of the 95% confidence interval on the mean. */
  ci95: number;
  n: number;
};

export type ReplicationResult = {
  runs: number;
  secondsPerRun: number;
  warmupS: number;
  avgSpeedKmh: RepStat;
  throughputPerMin: RepStat;
  longestQueueM: RepStat;
  co2RatePerMin: RepStat;
  avgTravelTimeS: RepStat;
  unmetVehPerHour: RepStat;
};

/* Student's t for a 95% two-sided interval, by degrees of freedom.
 *
 * Not the normal 1.96: at the run counts anyone will actually wait for (5-20)
 * that understates the interval by a fifth or more, which is exactly the range
 * where an honest error bar matters most. */
const T95: Record<number, number> = {
  1: 12.706, 2: 4.303, 3: 3.182, 4: 2.776, 5: 2.571, 6: 2.447, 7: 2.365,
  8: 2.306, 9: 2.262, 10: 2.228, 11: 2.201, 12: 2.179, 13: 2.160, 14: 2.145,
  15: 2.131, 16: 2.120, 17: 2.110, 18: 2.101, 19: 2.093, 20: 2.086,
  24: 2.064, 29: 2.045, 39: 2.023, 59: 2.001,
};
function tCrit(df: number): number {
  if (df <= 0) return 0;
  if (T95[df]) return T95[df];
  const keys = Object.keys(T95).map(Number).sort((a, b) => a - b);
  for (const k of keys) if (df < k) return T95[k];
  return 1.96;
}

function summarise(xs: number[]): RepStat {
  const n = xs.length;
  if (n === 0) return { mean: 0, sd: 0, ci95: 0, n: 0 };
  const mean = xs.reduce((a, b) => a + b, 0) / n;
  if (n === 1) return { mean, sd: 0, ci95: 0, n };
  // Sample standard deviation (n-1): these are a sample of possible runs, not
  // the population of them.
  const sd = Math.sqrt(xs.reduce((a, b) => a + (b - mean) ** 2, 0) / (n - 1));
  return { mean, sd, ci95: tCrit(n - 1) * (sd / Math.sqrt(n)), n };
}

export type RepProgress = { done: number; total: number; label: string };

/* Runs `runs` independent replications, yielding progress so a caller can keep
 * a UI responsive. Each replication is a fresh simulation on its own seed;
 * within a run, metrics are sampled repeatedly after the warm-up and averaged,
 * because a single end-of-run snapshot is itself just one more sample. */
export function* replicate(
  cfg: Omit<SimConfig, "seed"> & { seed?: number },
  interventions: Partial<Interventions>,
  opts: { runs?: number; secondsPerRun?: number; dt?: number; sampleEvery?: number } = {},
): Generator<RepProgress, ReplicationResult, void> {
  const runs = opts.runs ?? 10;
  const secondsPerRun = opts.secondsPerRun ?? 420;
  const dt = opts.dt ?? 0.05;
  const sampleEvery = opts.sampleEvery ?? 5;
  const warmupS = cfg.warmupS ?? DEFAULT_WARMUP_S;

  const speed: number[] = [], thru: number[] = [], queue: number[] = [];
  const co2: number[] = [], tt: number[] = [], unmet: number[] = [];

  for (let r = 0; r < runs; r++) {
    // Seeds spaced widely: adjacent seeds in a cheap PRNG can correlate, and
    // correlated replications would understate the variance the whole exercise
    // exists to measure.
    const seed = (cfg.seed ?? 12345) + r * 7919;
    const sim = new TrafficSim({ ...cfg, seed }, interventions);
    const s: number[] = [], t: number[] = [], q: number[] = [];
    const c: number[] = [], a: number[] = [], u: number[] = [];
    let nextSample = warmupS + sampleEvery;
    const steps = Math.round(secondsPerRun / dt);
    for (let i = 0; i < steps; i++) {
      sim.step(dt);
      if (sim.time >= nextSample) {
        nextSample += sampleEvery;
        const m = sim.metrics();
        if (!m.warm) continue;
        s.push(m.avgSpeedKmh); t.push(m.throughputPerMin); q.push(m.longestQueueM);
        c.push(m.co2RatePerMin); a.push(m.avgTravelTimeS); u.push(m.unmetVehPerHour);
      }
      // Yield between simulated seconds so a browser caller can paint.
      if (i % Math.round(1 / dt) === 0) {
        yield { done: r + i / steps, total: runs, label: `run ${r + 1} of ${runs}` };
      }
    }
    const avg = (xs: number[]) => (xs.length ? xs.reduce((p, n2) => p + n2, 0) / xs.length : 0);
    speed.push(avg(s)); thru.push(avg(t)); queue.push(avg(q));
    co2.push(avg(c)); tt.push(avg(a)); unmet.push(avg(u));
  }

  return {
    runs, secondsPerRun, warmupS,
    avgSpeedKmh: summarise(speed),
    throughputPerMin: summarise(thru),
    longestQueueM: summarise(queue),
    co2RatePerMin: summarise(co2),
    avgTravelTimeS: summarise(tt),
    unmetVehPerHour: summarise(unmet),
  };
}

/** Blocking convenience wrapper for headless callers (scripts, validation). */
export function replicateSync(
  cfg: Omit<SimConfig, "seed"> & { seed?: number },
  interventions: Partial<Interventions>,
  opts?: Parameters<typeof replicate>[2],
): ReplicationResult {
  const g = replicate(cfg, interventions, opts);
  let r = g.next();
  while (!r.done) r = g.next();
  return r.value;
}
