/**
 * Carriageway width along the NLEX corridor, by km-post range and direction.
 *
 * The sandbox needs to know how many lanes the selected stretch of road actually has, because a closure on a
 * 3-lane segment is a very different event from the same closure on a 4-lane one: it is the difference between
 * losing a third of capacity and losing a quarter.
 *
 * That figure is not in the warehouse (no lane column on nlex_exits, nothing in the schema), and neither the
 * NLEX Exits reference nor the manuscript states the corridor's lane configuration. This table was empty until
 * 2026-10-03 and every stretch fell back to 4 lanes; it now comes from OpenStreetMap, the same free source the
 * toll plazas use: the `lanes` tag on each North Luzon Expressway carriageway way, measured per direction
 * between consecutive interchanges by scenarios/tools/build_lanes.py, which writes the block below. Each entry
 * names its source and how much of the stretch carries that width. OSM is volunteer data; an official NLEX
 * lane plan, if the team gets one, should replace it (run the builder's way, or edit the block by hand with
 * its own `source`).
 *
 * Km-posts are those of lib/nlex-exits.ts (Balintawak 12, Sta. Ines 88.25). Ranges are [fromKm, toKm), and
 * `lanes` is through lanes in that direction, excluding shoulders, ramps and toll plaza booth fans.
 */

export type LaneSegment = {
  /** Km-post where this width begins, inclusive. Balintawak is 0. */
  fromKm: number;
  /** Km-post where it ends, exclusive. */
  toKm: number;
  /** Through lanes per direction, excluding shoulders and ramps. */
  lanes: number;
  /** Where the figure came from. Required — an unsourced entry is a guess. */
  source: string;
  /** The carriageway this width is for. Absent: both. */
  direction?: "NB" | "SB";
};

export const LANE_SEGMENTS: LaneSegment[] = [
  // BEGIN GENERATED by scenarios/tools/build_lanes.py — edit there, or replace with an official source.
  { fromKm: 12.0, toKm: 13.63, lanes: 4, direction: "NB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 4 lanes on 67% of this stretch" },
  { fromKm: 13.63, toKm: 15.44, lanes: 4, direction: "NB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 4 lanes on 55% of this stretch" },
  { fromKm: 15.44, toKm: 20.21, lanes: 4, direction: "NB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 4 lanes on 89% of this stretch" },
  { fromKm: 20.21, toKm: 23.73, lanes: 4, direction: "NB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 4 lanes on 87% of this stretch" },
  { fromKm: 23.73, toKm: 26.05, lanes: 4, direction: "NB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 4 lanes on 86% of this stretch" },
  { fromKm: 26.05, toKm: 27.2, lanes: 4, direction: "NB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 4 lanes on 100% of this stretch" },
  { fromKm: 27.2, toKm: 27.82, lanes: 4, direction: "NB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 4 lanes on 100% of this stretch" },
  { fromKm: 27.82, toKm: 28.81, lanes: 4, direction: "NB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 4 lanes on 100% of this stretch" },
  { fromKm: 28.81, toKm: 32.69, lanes: 4, direction: "NB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 4 lanes on 96% of this stretch" },
  { fromKm: 32.69, toKm: 33.09, lanes: 3, direction: "NB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 3 lanes on 100% of this stretch" },
  { fromKm: 33.09, toKm: 38.55, lanes: 3, direction: "NB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 3 lanes on 97% of this stretch" },
  { fromKm: 38.55, toKm: 45.33, lanes: 3, direction: "NB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 3 lanes on 92% of this stretch" },
  { fromKm: 45.33, toKm: 56.91, lanes: 3, direction: "NB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 3 lanes on 96% of this stretch" },
  { fromKm: 56.91, toKm: 65.78, lanes: 3, direction: "NB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 3 lanes on 98% of this stretch" },
  { fromKm: 65.78, toKm: 72.78, lanes: 2, direction: "NB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 2 lanes on 88% of this stretch" },
  { fromKm: 72.78, toKm: 81.15, lanes: 2, direction: "NB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 2 lanes on 92% of this stretch" },
  { fromKm: 81.15, toKm: 83.05, lanes: 2, direction: "NB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 2 lanes on 70% of this stretch" },
  { fromKm: 83.05, toKm: 85.23, lanes: 2, direction: "NB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 2 lanes on 71% of this stretch" },
  { fromKm: 85.23, toKm: 88.25, lanes: 2, direction: "NB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 2 lanes on 96% of this stretch" },
  { fromKm: 12.0, toKm: 13.63, lanes: 4, direction: "SB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 4 lanes on 62% of this stretch" },
  { fromKm: 13.63, toKm: 15.44, lanes: 4, direction: "SB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 4 lanes on 72% of this stretch" },
  { fromKm: 15.44, toKm: 20.21, lanes: 4, direction: "SB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 4 lanes on 75% of this stretch" },
  { fromKm: 20.21, toKm: 23.73, lanes: 4, direction: "SB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 4 lanes on 91% of this stretch" },
  { fromKm: 23.73, toKm: 26.05, lanes: 4, direction: "SB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 4 lanes on 100% of this stretch" },
  { fromKm: 26.05, toKm: 27.2, lanes: 4, direction: "SB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 4 lanes on 100% of this stretch" },
  { fromKm: 27.2, toKm: 27.82, lanes: 4, direction: "SB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 4 lanes on 100% of this stretch" },
  { fromKm: 27.82, toKm: 28.81, lanes: 4, direction: "SB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 4 lanes on 100% of this stretch" },
  { fromKm: 28.81, toKm: 32.69, lanes: 4, direction: "SB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 4 lanes on 96% of this stretch" },
  { fromKm: 32.69, toKm: 33.09, lanes: 3, direction: "SB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 3 lanes on 100% of this stretch" },
  { fromKm: 33.09, toKm: 38.55, lanes: 3, direction: "SB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 3 lanes on 95% of this stretch" },
  { fromKm: 38.55, toKm: 45.33, lanes: 3, direction: "SB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 3 lanes on 96% of this stretch" },
  { fromKm: 45.33, toKm: 56.91, lanes: 3, direction: "SB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 3 lanes on 99% of this stretch" },
  { fromKm: 56.91, toKm: 65.78, lanes: 3, direction: "SB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 3 lanes on 91% of this stretch" },
  { fromKm: 65.78, toKm: 72.78, lanes: 2, direction: "SB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 2 lanes on 91% of this stretch" },
  { fromKm: 72.78, toKm: 81.15, lanes: 2, direction: "SB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 2 lanes on 93% of this stretch" },
  { fromKm: 81.15, toKm: 83.05, lanes: 2, direction: "SB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 2 lanes on 83% of this stretch" },
  { fromKm: 83.05, toKm: 85.23, lanes: 2, direction: "SB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 2 lanes on 71% of this stretch" },
  { fromKm: 85.23, toKm: 88.25, lanes: 2, direction: "SB", source: "OpenStreetMap lanes tags (© OpenStreetMap contributors), read 2026-10-03: 2 lanes on 96% of this stretch" },
  // END GENERATED
];

/**
 * Lane count for the stretch between two km-posts.
 *
 * Returns the NARROWEST width the route passes through, not the width at either
 * end. A journey from a 5-lane section into a 3-lane one is governed by the
 * 3-lane pinch — that is where the queue forms, and simulating the wider figure
 * would understate every closure on the route.
 *
 * Returns null when the corridor table does not cover the whole span, so the
 * caller can say "unknown" rather than present a default as fact.
 */
export function lanesForSegment(fromKm: number, toKm: number, direction?: "NB" | "SB"): number | null {
  const table = forDirection(direction);
  if (table.length === 0) return null;

  const lo = Math.min(fromKm, toKm);
  const hi = Math.max(fromKm, toKm);
  // A zero-length route (same origin and destination) still has a width; treat
  // it as the single point rather than an empty span.
  const overlapping = table.filter((s) =>
    lo === hi ? lo >= s.fromKm && lo < s.toKm : s.fromKm < hi && s.toKm > lo,
  );
  if (overlapping.length === 0) return null;

  // Every kilometre of the route must be covered, or the narrowest known
  // section might not be the narrowest actual one.
  const covered = overlapping
    .map((s) => [Math.max(s.fromKm, lo), Math.min(s.toKm, hi)] as const)
    .sort((a, b) => a[0] - b[0]);
  let reach = lo;
  for (const [a, b] of covered) {
    if (a > reach + 1e-9) return null; // gap in the table
    reach = Math.max(reach, b);
  }
  if (reach < hi - 1e-9) return null;

  return Math.min(...overlapping.map((s) => s.lanes));
}

/** The entries that apply to one carriageway (those for it, and those for both); every entry without one. */
function forDirection(direction?: "NB" | "SB"): LaneSegment[] {
  return direction === undefined ? LANE_SEGMENTS : LANE_SEGMENTS.filter((s) => s.direction === undefined || s.direction === direction);
}

/** The sources behind a route's width, for showing provenance in the UI. */
export function laneSources(fromKm: number, toKm: number, direction?: "NB" | "SB"): string[] {
  const lo = Math.min(fromKm, toKm);
  const hi = Math.max(fromKm, toKm);
  return [
    ...new Set(
      forDirection(direction).filter((s) => s.fromKm < hi && s.toKm > lo).map((s) => s.source),
    ),
  ];
}
