/* GENERATED by app/dashboard/scenario-sandbox/scenarios/tools/build_toll_plazas.py — do not edit by hand.
 *
 * Every NLEX toll plaza road, from OpenStreetMap. (c) OpenStreetMap contributors,
 * available under the Open Database Licence (openstreetmap.org/copyright).
 * Read 2026-10-01 through the public Overpass API.
 *
 * One row per plaza ROAD: an interchange usually has one per movement and
 * direction (the exit off NB, the entry onto SB...). `lanes` is the road's lane
 * count at the booths, which on a plaza is its number of booth lanes; null where
 * the mapper did not record it. `km` is where the booth line projects onto the
 * corridor, on the same km-post scale as lib/nlex-exits.ts, and `offsetM` how far
 * off the expressway's centreline it stands. `directions` has both NB and SB
 * when one plaza serves traffic from both carriageways.
 *
 * This is volunteer-mapped data: good, not official. NLEX's own booth counts,
 * where they can be had, are better and should replace it.
 *
 * Written twice, identically: Front-End-Dashboard/lib (the sandbox draws the
 * plazas from it) and Back-End/src/data (the booth staffing plan caps each plaza
 * at the booths it has). The two packages cannot import from each other.
 */

export type OsmTollPlaza = {
  /** Interchange name, exactly as in lib/nlex-exits.ts. */
  exit: string;
  movement: "exit" | "entry" | "barrier";
  directions: ("NB" | "SB")[];
  lanes: number | null;
  km: number;
  offsetM: number;
  name: string;
  osmNode: number;
};

export const OSM_TOLL_PLAZAS_READ = "2026-10-01";

export const OSM_TOLL_PLAZAS: OsmTollPlaza[] = [
  { exit: "Balintawak", movement: "barrier", directions: ["NB"], lanes: 12, km: 12.0, offsetM: 32, name: "Balintawak Toll Plaza A", osmNode: 379019519 },
  { exit: "Balintawak", movement: "barrier", directions: ["NB"], lanes: 5, km: 12.0, offsetM: 59, name: "Balintawak Toll Plaza A", osmNode: 379019520 },
  { exit: "Balintawak", movement: "barrier", directions: ["NB"], lanes: 8, km: 12.14, offsetM: 32, name: "Balintawak Toll Plaza B", osmNode: 5720654257 },
  { exit: "Paso De Blas Valenzuela", movement: "entry", directions: ["SB"], lanes: 4, km: 15.365, offsetM: 31, name: "", osmNode: 1129127553 },
  { exit: "Paso De Blas Valenzuela", movement: "entry", directions: ["NB"], lanes: 3, km: 15.559, offsetM: 33, name: "", osmNode: 506851735 },
  { exit: "Meycauayan", movement: "entry", directions: ["SB"], lanes: 5, km: 20.034, offsetM: 50, name: "Meycauayan", osmNode: 441527355 },
  { exit: "Meycauayan", movement: "entry", directions: ["NB"], lanes: 3, km: 20.33, offsetM: 68, name: "Meycauayan", osmNode: 441527354 },
  { exit: "Marilao", movement: "entry", directions: ["SB"], lanes: 4, km: 23.55, offsetM: 200, name: "Marilao", osmNode: 1761916420 },
  { exit: "Marilao", movement: "entry", directions: ["NB"], lanes: 2, km: 23.933, offsetM: 112, name: "Marilao", osmNode: 1761823196 },
  { exit: "Cdv/Ph Arena", movement: "entry", directions: ["NB"], lanes: 2, km: 25.724, offsetM: 217, name: "Philippine Arena", osmNode: 4783122449 },
  { exit: "Cdv/Ph Arena", movement: "exit", directions: ["NB"], lanes: 3, km: 25.728, offsetM: 197, name: "Philippine Arena", osmNode: 4783122448 },
  { exit: "Cdv/Ph Arena", movement: "entry", directions: ["SB"], lanes: 4, km: 26.054, offsetM: 69, name: "Philippine Arena", osmNode: 7022784337 },
  { exit: "Bocaue Barrier", movement: "barrier", directions: ["SB"], lanes: 8, km: 27.011, offsetM: 16, name: "Bocaue Toll Plaza B", osmNode: 6340974730 },
  { exit: "Bocaue Barrier", movement: "barrier", directions: ["SB"], lanes: 24, km: 27.2, offsetM: 4, name: "Bocaue Toll Plaza A", osmNode: 379119563 },
  { exit: "Bocaue Barrier", movement: "entry", directions: ["SB"], lanes: 4, km: 27.205, offsetM: 65, name: "Bocaue Toll Plaza A", osmNode: 379119565 },
  { exit: "Bocaue Interchange", movement: "exit", directions: ["NB"], lanes: 4, km: 27.714, offsetM: 31, name: "Bocaue", osmNode: 8327487971 },
  { exit: "Bocaue Interchange", movement: "exit", directions: ["SB"], lanes: 3, km: 27.888, offsetM: 29, name: "Bocaue", osmNode: 1129127463 },
  { exit: "Bocaue Interchange", movement: "entry", directions: ["NB"], lanes: 3, km: 27.909, offsetM: 42, name: "", osmNode: 1081489208 },
  { exit: "Tambubong", movement: "exit", directions: ["NB"], lanes: 3, km: 28.652, offsetM: 189, name: "Tambubong", osmNode: 7025129278 },
  { exit: "Tambubong", movement: "entry", directions: ["NB"], lanes: 2, km: 28.84, offsetM: 43, name: "Tambubong", osmNode: 11129046035 },
  { exit: "Tambubong", movement: "entry", directions: ["SB"], lanes: 2, km: 28.883, offsetM: 122, name: "Tambubong", osmNode: 7025129268 },
  { exit: "Balagtas", movement: "exit", directions: ["NB"], lanes: 6, km: 33.583, offsetM: 525, name: "Balagtas Toll Plaza", osmNode: 2147281074 },
  { exit: "Balagtas", movement: "entry", directions: ["NB", "SB"], lanes: 3, km: 33.588, offsetM: 500, name: "Balagtas Toll Plaza", osmNode: 2147281086 },
  { exit: "Sta. Rita Guiguinto", movement: "exit", directions: ["NB"], lanes: 6, km: 38.511, offsetM: 124, name: "Santa Rita", osmNode: 480772480 },
  { exit: "Sta. Rita Guiguinto", movement: "entry", directions: ["NB"], lanes: 2, km: 38.519, offsetM: 112, name: "Santa Rita", osmNode: 480772504 },
  { exit: "Sta. Rita Guiguinto", movement: "entry", directions: ["SB"], lanes: 4, km: 38.57, offsetM: 163, name: "Santa Rita", osmNode: 481704792 },
  { exit: "Sta. Rita Guiguinto", movement: "exit", directions: ["SB"], lanes: 3, km: 38.579, offsetM: 171, name: "Santa Rita", osmNode: 148901956 },
  { exit: "Pulilan", movement: "exit", directions: ["NB"], lanes: 3, km: 45.184, offsetM: 64, name: "Pulilan", osmNode: 243676249 },
  { exit: "Pulilan", movement: "entry", directions: ["SB"], lanes: 2, km: 45.244, offsetM: 69, name: "Pulilan", osmNode: 148901195 },
  { exit: "Pulilan", movement: "entry", directions: ["NB"], lanes: 2, km: 45.422, offsetM: 68, name: "Pulilan", osmNode: 1129127394 },
  { exit: "Pulilan", movement: "exit", directions: ["SB"], lanes: 3, km: 45.51, offsetM: 56, name: "Pulilan", osmNode: 964505932 },
  { exit: "San Simon", movement: "exit", directions: ["NB"], lanes: 4, km: 56.723, offsetM: 5, name: "San Simon", osmNode: 1129127392 },
  { exit: "San Simon", movement: "entry", directions: ["SB"], lanes: 3, km: 56.782, offsetM: 64, name: "San Simon", osmNode: 1129127472 },
  { exit: "San Simon", movement: "entry", directions: ["NB"], lanes: 2, km: 57.084, offsetM: 73, name: "San Simon", osmNode: 448809409 },
  { exit: "San Simon", movement: "exit", directions: ["SB"], lanes: 2, km: 57.105, offsetM: 14, name: "San Simon", osmNode: 538627621 },
  { exit: "San Fernando", movement: "entry", directions: ["SB"], lanes: 5, km: 65.63, offsetM: 84, name: "San Fernando", osmNode: 457322052 },
  { exit: "San Fernando", movement: "exit", directions: ["SB"], lanes: 3, km: 65.833, offsetM: 86, name: "San Fernando", osmNode: 1129050391 },
  { exit: "San Fernando", movement: "exit", directions: ["NB"], lanes: 7, km: 65.9, offsetM: 143, name: "San Fernando", osmNode: 1129050334 },
  { exit: "San Fernando", movement: "entry", directions: ["NB"], lanes: 3, km: 65.912, offsetM: 161, name: "San Fernando", osmNode: 347274736 },
  { exit: "Mexico", movement: "exit", directions: ["NB", "SB"], lanes: 3, km: 73.073, offsetM: 174, name: "Mexico", osmNode: 1128955855 },
  { exit: "Mexico", movement: "entry", directions: ["NB", "SB"], lanes: 2, km: 73.078, offsetM: 163, name: "Mexico", osmNode: 1128955874 },
  { exit: "Angeles", movement: "entry", directions: ["NB", "SB"], lanes: 4, km: 81.15, offsetM: 334, name: "Angeles", osmNode: 322051815 },
  { exit: "Angeles", movement: "exit", directions: ["NB", "SB"], lanes: 6, km: 81.165, offsetM: 332, name: "Angeles", osmNode: 498715153 },
  { exit: "Dau", movement: "exit", directions: ["NB"], lanes: 2, km: 82.983, offsetM: 106, name: "Dau", osmNode: 12093526 },
  { exit: "Dau", movement: "entry", directions: ["NB"], lanes: 2, km: 83.082, offsetM: 33, name: "Dau", osmNode: 674048192 },
  { exit: "Dau", movement: "entry", directions: ["SB"], lanes: 2, km: 83.188, offsetM: 32, name: "Dau", osmNode: 4127292338 },
  { exit: "Dau", movement: "exit", directions: ["SB"], lanes: 2, km: 83.307, offsetM: 113, name: "Dau", osmNode: 317179566 },
  { exit: "Sta. Ines", movement: "barrier", directions: ["SB"], lanes: 3, km: 88.23, offsetM: 5, name: "Santa Ines Toll Plaza", osmNode: 4127294439 },
  { exit: "Sta. Ines", movement: "barrier", directions: ["NB"], lanes: 3, km: 88.239, offsetM: 21, name: "Santa Ines Toll Plaza", osmNode: 4127294438 },
];

/* Plazas that belong to an interchange but stand more than 900 m off the
 * expressway, on the road it connects to — the Harbor Link's own plaza, for one.
 * Traffic recorded for that interchange paid there, so at the junction itself the
 * movement has no booths. */
export const OSM_TOLL_PLAZAS_AWAY: OsmTollPlaza[] = [
  { exit: "NLEX Harbor Link", movement: "entry", directions: ["NB", "SB"], lanes: 5, km: 13.63, offsetM: 1842, name: "NLEX Mindanao Toll Plaza", osmNode: 771346159 },
  { exit: "NLEX Harbor Link", movement: "entry", directions: ["NB", "SB"], lanes: 3, km: 13.63, offsetM: 1732, name: "NLEX Mindanao Toll Plaza", osmNode: 5480697614 },
  { exit: "NLEX Harbor Link", movement: "entry", directions: ["NB", "SB"], lanes: 6, km: 14.759, offsetM: 2261, name: "Karuhatan Toll Plaza", osmNode: 3557388319 },
  { exit: "Sctex", movement: "entry", directions: ["SB"], lanes: 2, km: 85.827, offsetM: 1352, name: "Mabiga", osmNode: 967633043 },
  { exit: "Sctex", movement: "exit", directions: ["NB"], lanes: 2, km: 85.908, offsetM: 1379, name: "Mabiga", osmNode: 4157287291 },
];
